### PR TITLE
support wildcard replacement in toPath middleware

### PR DESCRIPTION
**Pull request by zaggino**
I've wanted to impelement what tests say, but run into some weird issue. First request works fine, all the others don't. Seems not to be an issue of my implementation since modifying one of the original tests has the same behaviour.

### CODE REVIEW

**Comment by zaggino** [comment]
@h2non can you take a look what could be the problem here?

**Comment by zaggino** [comment]
Ok - I've fixed it, sorry for a bit of spamming :)

**Comment by zaggino** [comment]
With this I'm able to do:
```
proxy
  .get('/api/*')
  .forward('https://api.domain.com')
  .toPath('/*')
```

**Comment by h2non** [comment]
@zaggino I did some refactors. Take a look and let me know: https://github.com/h2non/rocky/commit/697887bb3512e5229c9303348bf8e51c6e845c15

**Comment by h2non** [comment]
This feature is now available in `rocky@0.4.9`. Feel free to update your dependency tree.

**Comment by zaggino** [comment]
Thanks for the quick merge :)

**Comment by zaggino** [comment]
I've updated to `0.4.10` and can confirm everything works fine now. Thanks

**Comment by kevingilbert100** [comment]
This is not working

**Pull request merged**
